### PR TITLE
Added length delimited string versions of parsing methods

### PR DESCRIPTION
**Pull request by ik80**
Hi!

I added couple methods to parse length delimited strings. 

Parsing function is a copy-paste from null-terminated string, and its the same with length check after each increment.

Cold path strtod fallback conversions I just added a fixed length buffer which gets a copy from p, pe and run strtod on that instead.

Updated benchmarks. #12

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. This looks reasonable. What are your benchmark numbers telling you?

**Comment by ik80** [comment]
Obviously, I havent actually reworked the benchmark to test stream parsing vs stream + copy, which would be relevant test for inplace parsing. Otherwise its:

Windows Ryzen 7 3700X

=== trial 1 ===                                                                                                                                                                                                                                                                           fast_double_parser  868.16 MB/s                                                                                                                                                                                                                                                           fast_inplace_double_parser  872.63 MB/s                                                                                                                                                                                                                                                   strtod         77.02 MB/s                                                                                                                                                                                                                                                                 abslfromch     108.42 MB/s                                                                                                                                                                                                                                                                absl           82.24 MB/s                                                                                                                                                                                                                                                                 double-conv    158.55 MB/s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    === trial 2 ===                                                                                                                                                                                                                                                                           fast_double_parser  976.13 MB/s                                                                                                                                                                                                                                                           fast_inplace_double_parser  905.14 MB/s                                                                                                                                                                                                                                                   strtod         75.45 MB/s                                                                                                                                                                                                                                                                 abslfromch     108.86 MB/s                                                                                                                                                                                                                                                                absl           84.20 MB/s                                                                                                                                                                                                                                                                 double-conv    158.68 MB/s


Linux, Celeron J1900


=== trial 1 ===
fast_double_parser  206.72 MB/s
fast_inplace_double_parser  186.26 MB/s
strtod         24.51 MB/s
abslfromch     55.55 MB/s
absl           45.60 MB/s
double-conv    56.93 MB/s


=== trial 2 ===
fast_double_parser  205.21 MB/s
fast_inplace_double_parser  183.63 MB/s
strtod         24.46 MB/s
abslfromch     55.67 MB/s
absl           45.61 MB/s
double-conv    57.21 MB/s

**Comment by lemire** [comment]
Thank you. I will take it from here, soon.

**Comment by lemire** [comment]
I am not forgetting this.

**Comment by lemire** [comment]
I am merging to the develop branch. I will add a few tests and then merge to master.

**Comment by lemire** [comment]
So I added some tests and merged into master, with some documentation. Sorry for the delay and thanks for the contribution.

Ideally, we should really clean things up and avoid duplication, but we can do it later.

**Comment by ik80** [comment]
Usually people write code for pBegin pEnd version and reuse that for other versions, but it should do for now.

**Pull request merged**
